# Generated by Django 3.1 on 2020-08-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('price_unit', models.CharField(choices=[('tl', '₺'), ('euro', '€'), ('dollar', '$')], default='tl', max_length=150)),
                ('bathrooms', models.IntegerField()),
                ('square', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('selected_home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.homes')),
            ],
        ),
    ]
