# Generated by Django 3.1 on 2020-08-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_homes_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homes',
            old_name='logo',
            new_name='image',
        ),
    ]
