# Generated by Django 3.1 on 2020-08-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20200818_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='homes',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
