# Generated by Django 3.1 on 2020-08-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_auto_20200819_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='homes',
            name='type',
            field=models.CharField(choices=[('kiralik', 'kiralık'), ('satlik', 'satlık')], default='satlik', max_length=150),
        ),
    ]
