# Generated by Django 3.1 on 2020-08-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_homes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomesSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('price_unit2', models.CharField(choices=[('tl', '₺'), ('euro', '€'), ('dollar', '$')], default='tl', max_length=150)),
                ('type', models.CharField(default='satlik', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
