# Generated by Django 3.1 on 2020-08-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_homessecond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homessecond',
            old_name='type',
            new_name='type2',
        ),
    ]
