# Generated by Django 3.1 on 2020-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20200820_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomesSecond',
        ),
        migrations.AlterField(
            model_name='homes',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Home name'),
        ),
        migrations.AlterField(
            model_name='homes',
            name='type',
            field=models.CharField(choices=[('kiralik', 'kiralık'), ('satlik', 'satlık')], default='kiralik', max_length=150),
        ),
    ]
