# Generated by Django 3.1 on 2020-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20200920_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='bathrooms',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homes',
            name='parking',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homes',
            name='price',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homes',
            name='rooms',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homes',
            name='square',
            field=models.CharField(max_length=150),
        ),
    ]
