# Generated by Django 3.1 on 2020-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_auto_20200920_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='homes',
            name='status',
            field=models.BooleanField(default=True, verbose_name='gosterilsin mi?'),
        ),
    ]
