# Generated by Django 3.1 on 2020-09-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_homes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homes',
            name='status',
        ),
    ]
