# Generated by Django 3.1 on 2020-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_remove_homes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='type',
            field=models.CharField(choices=[('kiralik', 'kiralık'), ('satlik', 'satlık')], default='', max_length=150),
        ),
    ]
