# Generated by Django 3.1 on 2020-09-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20200921_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='type',
            field=models.CharField(choices=[('kiralik', 'kiralık'), ('satlik', 'satlık')], default='kiralik', max_length=150),
        ),
    ]
