# Generated by Django 3.1 on 2020-09-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_auto_20200922_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='price',
            field=models.CharField(max_length=150),
        ),
    ]
